version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.40.0-focal
    working_directory: ~/repo
    environment:
      # Playwright browsers are pre-installed in Docker image
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Update Playwright to latest version
          command: |
            echo "🔄 Updating Playwright to latest version..."
            npm install @playwright/test@latest
            echo "✅ Playwright updated to latest version"

      - run:
          name: Run linter
          command: npm run lint

      - run:
          name: Verify Playwright browsers
          command: |
            echo "🔍 Verifying Playwright browsers..."
            npx playwright --version
            echo "✅ Browsers are pre-installed in Docker image"

      - run:
          name: Clean old results
          command: node scripts/clean-allure-results.js

      - run:
          name: Run Playwright tests
          command: npx playwright test
          when: on_success

      - run:
          name: Generate Allure report
          command: node scripts/generate-simple-report.js
          when: always

      - run:
          name: Deploy to GitHub Pages
          command: |
            echo "🚀 Starting GitHub Pages deployment..."

            # Install GitHub CLI
            if ! command -v gh &> /dev/null; then
              echo "📦 Installing GitHub CLI..."
              # Use npm to install gh globally (no sudo required)
              npm install -g @github/cli
            fi

            # Configure git
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"

            # Clone gh-pages branch
            echo "📥 Cloning gh-pages branch..."
            if [ -d "gh-pages" ]; then
              rm -rf gh-pages
            fi
            git clone --branch gh-pages --single-branch https://github.com/RaffyRod/to-do-MVC-Playwright.git gh-pages

            # Copy report files
            echo "📋 Copying report files..."
            cp -r allure-report/* gh-pages/

            # Commit and push
            echo "💾 Committing changes..."
            cd gh-pages
            git add .
            git commit -m "Update test report - $(date)" || echo "No changes to commit"

            echo "🚀 Pushing to GitHub Pages..."
            git remote set-url origin https://$GITHUB_TOKEN@github.com/RaffyRod/to-do-MVC-Playwright.git
            git push origin gh-pages

            echo "✅ Successfully deployed to GitHub Pages!"
            echo "🌐 Report available at: https://raffyrod.github.io/to-do-MVC-Playwright/"
          environment:
            GITHUB_TOKEN: $GITHUB_TOKEN
          when: always

      - store_artifacts:
          path: allure-report/
          destination: allure-report
          when: always

      - store_artifacts:
          path: test-results/
          destination: test-results
          when: always

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

workflows:
  test-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: main
