version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.0
    working_directory: ~/repo
    environment:
      # Optimize Playwright downloads
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: false
      PLAYWRIGHT_DOWNLOAD_HOST: https://playwright.download.prss.microsoft.com
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - restore_cache:
          keys:
            - v1-playwright-browsers-{{ checksum "package-lock.json" }}
            - v1-playwright-browsers-

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Update Playwright to latest version
          command: |
            echo "🔄 Updating Playwright to latest version..."
            npm install @playwright/test@latest
            echo "✅ Playwright updated to latest version"

      - run:
          name: Run linter
          command: npm run lint

      - run:
          name: Install Playwright browsers
          command: |
            echo "📦 Installing Playwright browsers (latest version)..."

            # Check if browsers are already cached
            if [ -d "$HOME/.cache/ms-playwright" ] && [ "$(ls -A $HOME/.cache/ms-playwright)" ]; then
              echo "✅ Browsers found in cache, updating to latest..."
              npx playwright install --with-deps
            else
              echo "📥 Browsers not in cache, downloading latest versions..."
              # Install only required browsers for faster setup
              npx playwright install chromium firefox webkit --with-deps
            fi

            # Verify browser versions
            echo "🔍 Installed browser versions:"
            npx playwright --version
            echo "✅ Browsers installed successfully"

      - run:
          name: Clean old results
          command: node scripts/clean-allure-results.js

      - run:
          name: Run Playwright tests
          command: npx playwright test
          when: on_success

      - run:
          name: Generate Allure report
          command: node scripts/generate-simple-report.js
          when: always

      - run:
          name: Deploy to GitHub Pages
          command: |
            echo "🚀 Starting GitHub Pages deployment..."

            # Install GitHub CLI
            if ! command -v gh &> /dev/null; then
              echo "📦 Installing GitHub CLI..."
              curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
              sudo apt update && sudo apt install gh -y
            fi

            # Configure git
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"

            # Clone gh-pages branch
            echo "📥 Cloning gh-pages branch..."
            if [ -d "gh-pages" ]; then
              rm -rf gh-pages
            fi
            git clone --branch gh-pages --single-branch https://github.com/RaffyRod/to-do-MVC-Playwright.git gh-pages

            # Copy report files
            echo "📋 Copying report files..."
            cp -r allure-report/* gh-pages/

            # Commit and push
            echo "💾 Committing changes..."
            cd gh-pages
            git add .
            git commit -m "Update test report - $(date)" || echo "No changes to commit"

            echo "🚀 Pushing to GitHub Pages..."
            git remote set-url origin https://$GITHUB_TOKEN@github.com/RaffyRod/to-do-MVC-Playwright.git
            git push origin gh-pages

            echo "✅ Successfully deployed to GitHub Pages!"
            echo "🌐 Report available at: https://raffyrod.github.io/to-do-MVC-Playwright/"
          environment:
            GITHUB_TOKEN: $GITHUB_TOKEN
          when: always

      - store_artifacts:
          path: allure-report/
          destination: allure-report
          when: always

      - store_artifacts:
          path: test-results/
          destination: test-results
          when: always

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - save_cache:
          paths:
            - ~/.cache/ms-playwright
          key: v1-playwright-browsers-{{ checksum "package-lock.json" }}

workflows:
  test-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: main
